name: Update data index

on:
  push:
    paths:
      - "data/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Generate data-index.json
        run: |
          echo "[" > data-index.json
          find data -type f -name '*.json' | sort | sed 's/^/  "/; s/$/"/; $!s/$/,/' >> data-index.json
          echo "]" >> data-index.json

      - name: Commit and push data-index.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data-index.json
          git commit -m "Update data-index.json [skip ci]" || echo "No changes"
          git push
